runtime: python27
api_version: 1
threadsafe: true
version: 20160924

handlers:
- url: /admin/.*
  script: admin.handlers
  login: admin
- url: /.*
  script: frontend.handlers

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
